//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Companies = new HashSet<Company>();
            this.SubDomains = new HashSet<SubDomain>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int ClientId { get; set; }
        public int UserId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<SubDomain> SubDomains { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
