//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public int ComplainId { get; set; }
        public string Description { get; set; }
        public int ComplainSeverityListItemId { get; set; }
        public bool ConsultManagement { get; set; }
        public int ComplainStatusListItemId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ListItem ListItem { get; set; }
        public virtual ListItem ListItem1 { get; set; }
    }
}
