//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public int EmployeeInformationId { get; set; }
        public int EmployeeId { get; set; }
        public int ContactNumber { get; set; }
        public int MobileNumber { get; set; }
        public string PersonalEmail { get; set; }
        public int GenderListItemId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertUserId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ListItem ListItem { get; set; }
    }
}
