//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Complains = new HashSet<Complain>();
            this.EmployeeInformations = new HashSet<EmployeeInformation>();
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.EmployeeLeaveDetails = new HashSet<EmployeeLeaveDetail>();
            this.EmployeeSalaries = new HashSet<EmployeeSalary>();
            this.SalaryTransactions = new HashSet<SalaryTransaction>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int EmployeeId { get; set; }
        public string Email { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Passsword { get; set; }
        public bool IsActive { get; set; }
        public int CompanyId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EmployeeInformation> EmployeeInformations { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<EmployeeLeaveDetail> EmployeeLeaveDetails { get; set; }
        public virtual ICollection<EmployeeSalary> EmployeeSalaries { get; set; }
        public virtual ICollection<SalaryTransaction> SalaryTransactions { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
