//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveDetail
    {
        public int EmployeeLeaveDetailId { get; set; }
        public int EmployeeId { get; set; }
        public int LeaveId { get; set; }
        public int Days { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave Leave { get; set; }
    }
}
