//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public int EmployeeLeaveId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> LeaveId { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int LeaveStatusListItemId { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApprovedUserId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave Leave { get; set; }
        public virtual User User { get; set; }
        public virtual ListItem ListItem { get; set; }
    }
}
