//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public Leave()
        {
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.EmployeeLeaveDetails = new HashSet<EmployeeLeaveDetail>();
        }
    
        public int LeaveId { get; set; }
        public string LeaveName { get; set; }
        public int CompanyId { get; set; }
        public int Days { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<EmployeeLeaveDetail> EmployeeLeaveDetails { get; set; }
    }
}
