//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public ListItem()
        {
            this.Complains = new HashSet<Complain>();
            this.Complains1 = new HashSet<Complain>();
            this.EmployeeInformations = new HashSet<EmployeeInformation>();
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.Plans = new HashSet<Plan>();
            this.PlanDurations = new HashSet<PlanDuration>();
            this.SalaryTransactions = new HashSet<SalaryTransaction>();
            this.SalaryTransactions1 = new HashSet<SalaryTransaction>();
            this.SalaryTransactions2 = new HashSet<SalaryTransaction>();
            this.SystemUserInformations = new HashSet<SystemUserInformation>();
            this.Tickets = new HashSet<Ticket>();
            this.Tickets1 = new HashSet<Ticket>();
            this.UserInformations = new HashSet<UserInformation>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int ListItemId { get; set; }
        public int ListItemCategoryId { get; set; }
        public string ListItemName { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual ICollection<Complain> Complains1 { get; set; }
        public virtual ICollection<EmployeeInformation> EmployeeInformations { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ListItemCategory ListItemCategory { get; set; }
        public virtual ICollection<Plan> Plans { get; set; }
        public virtual ICollection<PlanDuration> PlanDurations { get; set; }
        public virtual ICollection<SalaryTransaction> SalaryTransactions { get; set; }
        public virtual ICollection<SalaryTransaction> SalaryTransactions1 { get; set; }
        public virtual ICollection<SalaryTransaction> SalaryTransactions2 { get; set; }
        public virtual ICollection<SystemUserInformation> SystemUserInformations { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Ticket> Tickets1 { get; set; }
        public virtual ICollection<UserInformation> UserInformations { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
