//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int PlanId { get; set; }
        public string Name { get; set; }
        public int PlanDurationListItemId { get; set; }
        public decimal Price { get; set; }
        public int CompanyLimit { get; set; }
        public int IsActive { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual ListItem ListItem { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
