//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryRateSetup
    {
        public int SalaryRateSetupId { get; set; }
        public int CompanyId { get; set; }
        public string RateName { get; set; }
        public decimal From { get; set; }
        public decimal Upto { get; set; }
        public double Rate { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
