//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryTransaction
    {
        public int SalaryTransactionId { get; set; }
        public int EmployeeId { get; set; }
        public int SalaryPaymentTypeListItemId { get; set; }
        public System.DateTime PaidFromDate { get; set; }
        public System.DateTime PaidUptoDate { get; set; }
        public int PaymentMethodListItemId { get; set; }
        public decimal SalaryAmount { get; set; }
        public Nullable<double> EmployeeProvidentFundRate { get; set; }
        public Nullable<decimal> EmployeeProvidentFundAmount { get; set; }
        public Nullable<double> CompanyProvidentFundRate { get; set; }
        public Nullable<decimal> CompanyProvidentFundAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal MiscellenousAmount { get; set; }
        public int SalaryStatusListItemId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ListItem ListItem { get; set; }
        public virtual ListItem ListItem1 { get; set; }
        public virtual ListItem ListItem2 { get; set; }
        public virtual User User { get; set; }
    }
}
