//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public SystemUser()
        {
            this.SystemUserInformations = new HashSet<SystemUserInformation>();
            this.SystemUserInformations1 = new HashSet<SystemUserInformation>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual ICollection<SystemUserInformation> SystemUserInformations { get; set; }
        public virtual ICollection<SystemUserInformation> SystemUserInformations1 { get; set; }
    }
}
